name: Python Application Test with Github Actions 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v1
        with: 
          python-version: 3.12.7
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: extract 
        run: make extract 
      - name: transform
        run: make transform
      - name: format
        run: make format
